### ISSUE TITLE
Ideas for formatting code examples

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/phoenix-book#24]
This issue is intended to help us decide on which format we should use for the code examples.

Currently, we use the following format:

```
iex(1)> defmodule Area do
...(1)>   def circle(radius) do
...(1)>     pi() * radius * radius
...(1)>   end
...(1)>
...(1)>   defp pi do
...(1)>     3.14
...(1)>   end
...(1)> end
{:module, Area, ...
iex(2)> Area.circle(10)
314.0
iex(3)> Area.pi <3>
** (UndefinedFunctionError) function Area.pi/0 is undefined or private
    Area.pi()
```

## Other formats

The Elixir getting-started guide (example taken from the [Modules and Functions page](https://elixir-lang.org/getting-started/modules-and-functions.html):

```
iex> defmodule Math do
...>   def sum(a, b) do
...>     a + b
...>   end
...> end

iex> Math.sum(1, 2)
3
```

Compared with our current format, the getting-started guide does not include the command numbers, and it does not show the module return value (it displays a blank line instead).

If we find any examples of other formats, we can add them in the comments below.

**Comment by wintermeyer** [comment]
I agree with @riverrun about this. As a side benefit we would safe some real estate.
